services:
  client:
    build: 
      context: ./client
    ports:
      - "5173:80"
    # Reinicia el contenedor a menos que se detenga manualmente
    restart: unless-stopped
    networks:
      - demo-net

networks:
  demo-net:
    external: true

